name= "pastebin-worker"
compatibility_date = "2023-11-28"
account_id= "c4caffd14913c96c70fc10dda126447c"
main = "src/index.ts"
workers_dev = false

vars = { ENVIRONMENT = "production" }
route = { pattern = "paste.hanze.icu", custom_domain = true }

kv_namespaces = [
  { binding = "PB", id = "22abfbd2fbd143269c76aba06510111c" },
  { binding = "PBIMGS", id ="09f63b6577d54da682ac737833aa9472" }
]

[site]
bucket = "./static/dist"
